name: timeago
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 3.6.1
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  intl: ">=0.18.0 <0.20.0"

dev_dependencies:
  test: ^1.24.9
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.7
  lints: ^3.0.0
